In [3]:
import pandas as pd
file_path="D:/Documents/Projects/Intern/Datasets_Provided/Churn Prdiction Data/churn-bigml-80.csv"
df = pd.read_csv(file_path)
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [6]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 2666
Columns: 20

In [4]:
df_clean = df.copy()

In [5]:
missing_values = df_clean.isnull().sum()

missing_values

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [6]:
print("Total missing values:", df_clean.isnull().sum().sum())

Total missing values: 0

In [7]:
duplicate_count = df_clean.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [8]:
df_clean = df_clean.drop_duplicates()

In [9]:
df_clean.dtypes

State                         str
Account length              int64
Area code                   int64
International plan            str
Voice mail plan               str
Number vmail messages       int64
Total day minutes         float64
Total day calls             int64
Total day charge          float64
Total eve minutes         float64
Total eve calls             int64
Total eve charge          float64
Total night minutes       float64
Total night calls           int64
Total night charge        float64
Total intl minutes        float64
Total intl calls            int64
Total intl charge         float64
Customer service calls      int64
Churn                        bool
dtype: object

In [10]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 2666 entries, 0 to 2665
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State                   2666 non-null   str
 1   Account length          2666 non-null   int64
 2   Area code               2666 non-null   int64
 3   International plan      2666 non-null   str
 4   Voice mail plan         2666 non-null   str
 5   Number vmail messages   2666 non-null   int64
 6   Total day minutes       2666 non-null   float64
 7   Total day calls         2666 non-null   int64
 8   Total day charge        2666 non-null   float64
 9   Total eve minutes       2666 non-null   float64
 10  Total eve calls         2666 non-null   int64
 11  Total eve charge        2666 non-null   float64
 12  Total night minutes     2666 non-null   float64
 13  Total night calls       2666 non-null   int64
 14  Total night charge      2666 non-null   float64
 15  Total intl minutes      2666 non-null   float64
 16  Total intl calls        2666 non-null   int64
 17  Total intl charge       2666 non-null   float64
 18  Customer service calls  2666 non-null   int64
 19  Churn                   2666 non-null   bool
dtypes: bool(1), float64(8), int64(8), str(3)
memory usage: 398.5 KB

In [11]:
df_clean.columns.tolist()

['State',
 'Account length',
 'Area code',
 'International plan',
 'Voice mail plan',
 'Number vmail messages',
 'Total day minutes',
 'Total day calls',
 'Total day charge',
 'Total eve minutes',
 'Total eve calls',
 'Total eve charge',
 'Total night minutes',
 'Total night calls',
 'Total night charge',
 'Total intl minutes',
 'Total intl calls',
 'Total intl charge',
 'Customer service calls',
 'Churn']

In [12]:
categorical_columns = [
    "State",
    "International plan",
    "Voice mail plan",
    "Churn"
]

for column in categorical_columns:
    print("\n", column)
    print(df_clean[column].value_counts(dropna=False))

 State
State
WV    88
MN    70
NY    68
VA    67
OH    66
AL    66
WY    66
OR    62
WI    61
NV    61
MD    60
UT    60
CO    59
CT    59
MI    58
VT    57
ID    56
NC    56
TX    55
FL    54
IN    54
MT    53
KS    52
OK    52
MA    52
MO    51
DE    51
NJ    50
GA    49
SD    49
ME    49
SC    49
RI    48
WA    48
MS    48
AR    47
AZ    45
NE    45
IL    45
DC    45
NM    44
HI    44
ND    44
NH    43
AK    43
KY    43
TN    41
IA    38
PA    36
LA    35
CA    24
Name: count, dtype: int64

 International plan
International plan
No     2396
Yes     270
Name: count, dtype: int64

 Voice mail plan
Voice mail plan
No     1933
Yes     733
Name: count, dtype: int64

 Churn
Churn
False    2278
True      388
Name: count, dtype: int64

In [13]:
for column in categorical_columns:
    print(column, ":", df_clean[column].unique())

State : <StringArray>
['KS', 'OH', 'NJ', 'OK', 'AL', 'MA', 'MO', 'WV', 'RI', 'IA', 'MT', 'ID', 'VT',
 'VA', 'TX', 'FL', 'CO', 'AZ', 'NE', 'WY', 'IL', 'NH', 'LA', 'GA', 'AK', 'MD',
 'AR', 'WI', 'OR', 'DE', 'IN', 'UT', 'CA', 'SD', 'NC', 'WA', 'MN', 'NM', 'NV',
 'DC', 'NY', 'KY', 'ME', 'MS', 'MI', 'SC', 'TN', 'PA', 'HI', 'ND', 'CT']
Length: 51, dtype: str
International plan : <StringArray>
['No', 'Yes']
Length: 2, dtype: str
Voice mail plan : <StringArray>
['Yes', 'No']
Length: 2, dtype: str
Churn : [False  True]

In [14]:
numeric_columns = df_clean.select_dtypes(include="number").columns

negative_counts = (df_clean[numeric_columns] < 0).sum()
negative_counts[negative_counts > 0]

Series([], dtype: int64)

In [15]:
output_path = "cleaned_churn_data.csv"

df_clean.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [16]:
saved_df = pd.read_csv(output_path)

print(saved_df.shape)
saved_df.head()

(2666, 20)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False